package bg.tu_varna.sit.a2.f22621613.grammar.algorithms;

import bg.tu_varna.sit.a2.f22621613.grammar.contextFreeGrammar.ContextFreeGrammar;

import java.util.*;
/**
 * This class implements the CYK (Cocke-Younger-Kasami) algorithm for parsing strings
 * based on a given context-free grammar in Chomsky Normal Form (CNF).
 */
public class CYKAlgorithm {
    private static final char START_SYMBOL = 'S';
    private ContextFreeGrammar grammar;

    /**
     * Constructs a CYKAlgorithm instance with the specified context-free grammar.
     *
     * @param grammar The context-free grammar to be used for parsing.
     */
    public CYKAlgorithm(ContextFreeGrammar grammar) {
        this.grammar = grammar;
    }

    /**
     * Parses the input string to determine if it can be generated by the grammar.
     *
     * @param input The input string to be parsed.
     * @return True if the input string can be generated by the grammar, false otherwise.
     */
    public boolean parse(String input) {
        int n = input.length();
        Map<Character, List<Character>>[][] table = new Map[n][n];

        for (int i = 0; i < n; i++) {
            for (int j = 0; j < n; j++) {
                table[i][j] = new HashMap<>();
                if (i == j) {
                    table[i][j].computeIfAbsent(START_SYMBOL, l -> new ArrayList<>()).add(START_SYMBOL);
                }
            }
        }

        for (int i = 0; i < n; i++) {
            char symbol = input.charAt(i);
            for (Map.Entry<Character, List<String>> entry : grammar.getRules().entrySet()) {
                char nonTerminal = entry.getKey();
                List<String> productions = entry.getValue();
                for (String production : productions) {
                    int arrowIndex = production.indexOf("->");
                    if (arrowIndex != -1 && arrowIndex < production.length() - 2) {
                        char left = production.charAt(arrowIndex - 1);
                        String rhs = production.substring(arrowIndex + 2).trim();
                        for (char rhsChar : rhs.toCharArray()) {
                            if (rhsChar == symbol) {
                                table[i][i].computeIfAbsent(nonTerminal, k -> new ArrayList<>()).add(left);
                                break;
                            }
                        }
                    }
                }
            }
        }

        for (int len = 2; len <= n; len++) {
            for (int i = 0; i <= n - len; i++) {
                int j = i + len - 1;
                for (int k = i; k < j; k++) {
                    for (Map.Entry<Character, List<String>> entry : grammar.getRules().entrySet()) {
                        char nonTerminal = entry.getKey();
                        List<String> productions = entry.getValue();
                        for (String production : productions) {
                            int arrowIndex = production.indexOf("->");
                            if (arrowIndex != -1 && arrowIndex < production.length() - 2) {
                                char left = production.charAt(arrowIndex - 1);
                                String rhs = production.substring(arrowIndex + 2).trim();
                                for (int r = 0; r < rhs.length(); r++) {
                                    char right = rhs.charAt(r);
                                    if (table[i][k].containsKey(left) && table[k + 1][j].containsKey(right)) {
                                        table[i][j].computeIfAbsent(nonTerminal, l -> new ArrayList<>()).add(nonTerminal);
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        return table[0][n - 1].containsKey(START_SYMBOL);
    }
}

